### ISSUE TITLE
是否可以Windows上也这样

### ISSUE THREAD

**Issue by 760985933** [iamjohnnyzhuang/finder#1]
因为使用XSHELL一个个添加地址密码也很麻烦我想的是在Windows上也这样，不知道如何下手 刚学 Python写的话只会输入好ip等内容那种登录

**Comment by Jax-Rene** [comment]
Xshell已经算比较好用了，建议先了解下xshell的一些使用方法。
如果服务器太多，可以考虑弄个脚本导入
